import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-800 text-white flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
            <div className="hidden sm:ml-6 sm:block ">
                <div className="flex space-x-4 ">
                  <a href="/" className="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">หน้าหลัก</a>
                  <a href="/setting" className="text-white hover:bg-gray-500 hover:text-white rounded-md px-3 py-2 text-sm font-medium">ผู้ใช้งาน</a>
                  <a href="/" className="text-gray-100 hover:bg-gray-500 hover:text-white rounded-md px-3 py-2 text-sm font-medium">อาคาร</a>
                  <a href="/" className="text-gray-100 hover:bg-gray-500 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Calendar</a>
                </div>
            </div>
          </div>
          
          
        {children}
        
      </body>
    </html>
  );
}
